### ISSUE TITLE
Solr Docker Image only creates test core, needs dev core created as well

### ISSUE THREAD

**Issue by murny** [ualbertalib/discovery#1282]
Using the lightweight docker-compose.yml, I am having trouble running discovery on local as Solr isn't being set up properly? It seems to only create the `discovery-test` core and not both test and dev (`discovery`) cores.

![image](https://user-images.githubusercontent.com/1930474/45966980-d5336300-bfe9-11e8-9da7-1b1fb0279337.png)

Apparently this is due to the entrypoint command wiping out the `CMD` in the dockerfile (instead of appending it). Which is deemed `won't fix` in docker-compose. More info here: https://github.com/docker/compose/issues/3140

So because of this I'd assume only `docker-compose.lightweight.yml` is affected because it uses the entrypoint command: 

```
  solr:
    image: ualbertalib/blacklight_solr_conf
    ports:
       - "8983:8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - solr-precreate
      - discovery-test
      - /myconfig
```

 But for the regular `docker-compose.yml` I doesn't look like a test core gets created?

```
  solr:
    restart: always
    image: ualbertalib/blacklight_solr_conf
    volumes:
      - solr:/opt/solr/server/solr/mycores
```
So this is also a problem as well, as we need both dev and test cores setup for development.

Was there a particular reason why we avoided duplicating the way Jupiter sets up the Solr docker image for development and test?
